version: BuildNr.{build}

init:
- ps: $commit = $env:appveyor_repo_commit.SubString(0,7)
- ps: $timestamp = $env:appveyor_repo_commit_timestamp.SubString(0,10)
- ps: Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch, $commit, $timestamp)

image: Visual Studio 2015

#branches:
#    only:
#      - master

# clone directory
clone_folder: c:\projects\peripheral.xarcade

# fetch repository as zip archive
shallow_clone: true

environment:
  app_id: peripheral.xarcade

  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release

build_script:
  - call "%VS140COMNTOOLS%..\..\VC\bin\vcvars32.bat"
  - set cur_dir=%cd%
  - cd ..
  - git clone --depth=1 https://github.com/xbmc/xbmc.git
  - cd %app_id%
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DADDONS_TO_BUILD=%app_id% -DCMAKE_BUILD_TYPE=%CONFIG% -DADDON_SRC_PREFIX=../.. -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
  - cmake --build "%cur_dir%\build" --target %app_id%